package View;

import Logic.HighScoreManager;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JLabel;

// this view class is a panel that shows top highscores
// submit of last highscore is happening through this class
// creates and holds HighScoreManager object


/**
 *
 * @author user
 */
public class HighScoreView extends javax.swing.JPanel {
    
    private ArrayList<JLabel> labelList;
    private HighScoreManager manager;
    Data.HighScoreList list;
    /**
     * Creates new form HighScoreView
     */
    public HighScoreView() throws IOException {
        manager = new HighScoreManager();
        //manager.submitLastScore("ayse");       
        //updateScores();
        list = new Data.HighScoreList();
        labelList = new ArrayList<JLabel>();
           
        initComponents();
        loadLabels();
        writeScores();      
    }
    
    // it takes highscores from highscore manager and refreshes itself.
    public void updateScores() {
        manager = new HighScoreManager();
        manager.getHighScoreList();
    }
    
    // it submit the current game's Score.
    public void submitLastScore(String name) {
        
    }
    
    //This method writes the high scores and their owners to on labels
    private void writeScores() throws IOException{
        list =  manager.getHighScoreList();
        int i = 0;
        int t = list.getHighScoreNames().size();
        while(i != t){
            String name = list.getHighScoreNames().get(i);
            int score = list.getHighPoints().get(i);
            String labelStr = labelList.get(i).getText();
            labelStr = labelStr.substring(0, 3);
            labelStr = labelStr + name + " - " + score;
            labelList.get(i).setText(labelStr);
            i ++;
        }
    }
    
    private void loadLabels(){
        labelList.add(firstLabel);
        labelList.add(secondLabel);
        labelList.add(thirdLabel);
        labelList.add(forthLabel);
        labelList.add(fifthLabel);
        labelList.add(sixthLabel);
        labelList.add(seventhLabel);
        labelList.add(eightLabel);
        labelList.add(ninthLabel);
        labelList.add(tenthLabel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        fifthLabel = new javax.swing.JLabel();
        thirdLabel = new javax.swing.JLabel();
        seventhLabel = new javax.swing.JLabel();
        sixthLabel = new javax.swing.JLabel();
        eightLabel = new javax.swing.JLabel();
        forthLabel = new javax.swing.JLabel();
        ninthLabel = new javax.swing.JLabel();
        tenthLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HIGH SCORES");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        firstLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        firstLabel.setText("1. -");
        firstLabel.setName("firstPlayerLabel");

        secondLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        secondLabel.setText("2. -");
        secondLabel.setName("firstPlayerLabel");

        fifthLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fifthLabel.setText("5. -");
        fifthLabel.setName("firstPlayerLabel");

        thirdLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        thirdLabel.setText("3. -");
        thirdLabel.setName("firstPlayerLabel");

        seventhLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        seventhLabel.setText("7. -");
        seventhLabel.setName("firstPlayerLabel");

        sixthLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        sixthLabel.setText("6. -");
        sixthLabel.setName("firstPlayerLabel");

        eightLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        eightLabel.setText("8. -");
        eightLabel.setName("firstPlayerLabel");

        forthLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        forthLabel.setText("4. -");
        forthLabel.setName("firstPlayerLabel");

        ninthLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ninthLabel.setText("9. -");
        ninthLabel.setName("firstPlayerLabel");

        tenthLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tenthLabel.setText("10. -");
        tenthLabel.setName("firstPlayerLabel");

        backButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backButton.setText("Back To Main Menu");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(thirdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(forthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ninthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seventhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fifthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tenthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(sixthLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(secondLabel)
                                .addGap(0, 61, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(seventhLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdLabel)
                    .addComponent(eightLabel))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninthLabel)
                    .addComponent(forthLabel))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fifthLabel)
                    .addComponent(tenthLabel))
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
        ViewController.getInstance().showMainMenu();
    }                                       

    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JLabel eightLabel;
    private javax.swing.JLabel fifthLabel;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel forthLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ninthLabel;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel seventhLabel;
    private javax.swing.JLabel sixthLabel;
    private javax.swing.JLabel tenthLabel;
    private javax.swing.JLabel thirdLabel;
    // End of variables declaration
}